import { GlobalContext } from "@/GlobalContext";
import Head from "next/head";
import { useCallback, useRef, useContext } from "react";
import Table from "../components/Table";
import TableHeader from "../components/TableHeader";

export default function Home() {
  const GlobalState = useContext(GlobalContext);
  const { state, dispatch } = GlobalState;

  let debounceRef = useRef();

  const customDebounce = useCallback((cb, delay = 100) => {
    return (...args) => {
      clearTimeout(debounceRef.current);
      debounceRef.current = setTimeout(() => {
        cb(...args);
      }, delay);
    };
  }, []);

  const handlePress = () => {
    customDebounce(() => alert("Button pressed!"), 500)();
  };

  const handleChange = (e) => {
    customDebounce(
      () =>
        dispatch({
          type: "SET_NAME",
          name: e.target.value,
        }),
      1000
    )();
  };

  return (
    <>
      <Head>
        <title>Technical Test Interview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2>1. Debounce function</h2>
        <button onClick={handlePress}>Press Me</button>
        <h2>2. React Context</h2>
        <div>Name: {state.name}</div>
        <div>Age: {state.age}</div>
        <div>Hobby: {state.hobby}</div>
        <label>Set your name here...</label>
        <input type="text" onChange={handleChange} />
        <div style={{ height: 100 }} /> {/** separator */}
        <h2>3. Table with custom hook and context</h2>
        <TableHeader />
        <Table />
      </div>
    </>
  );
}
